### ISSUE TITLE
div v. span in buttons validation

### ISSUE THREAD

**Issue by badcat** [jussivirtanen/full-stack-ui#1]
These are all really nice - Congrats! 🎉
Minor suggestion - I think divs in buttons do not validate. Perhaps switch to spans with display inline-block? (e.g. Lesson 2-save-button )

**Comment by jussivirtanen** [comment]
Thanks @badcat, good catch! I added a note on this to that lesson.

![CleanShot 2020-10-26 at 08 24 34](https://user-images.githubusercontent.com/3430121/97140193-bffb0680-1764-11eb-9715-d424e05f1e69.png)
